# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Make these non-fatal (ignore specific error types)
    deprecated_member_use: ignore
    unnecessary_import: ignore
    unused_import: ignore
    prefer_const_constructors: ignore
    use_build_context_synchronously: ignore
    unused_local_variable: ignore
    unused_element: ignore
    prefer_const_literals_to_create_immutables: ignore
    sized_box_for_whitespace: ignore
    curly_braces_in_flow_control_structures: ignore
    await_only_futures: ignore

  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/build/**'

linter:
  rules:
    # Keep only the most important rules
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - camel_case_types
    - empty_constructor_bodies
    - library_names
    - no_duplicate_case_values
    - null_closures
    - prefer_iterable_whereType
    - slash_for_doc_comments
    - super_goes_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas