workflows:
  shorebird-release-apk:
    name: Shorebird Release (Android APK)
    
    # 1. TRIGGERS: Only run this workflow when a new tag is created.
    triggering:
      # FIX 1: Set branch to 'main' and use 'ignore' to disable push builds.
      # This is the correct way to ignore pushes in Codemagic YAML.
      branch:
        - pattern: main
          ignore: true
          
      # FIX 2: Correct indentation for tag structure
      tag:
        pattern: v*.*.*
        
    # 2. ENVIRONMENT: Define the environment the build will run in.
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      # Define environment variables. These variables are references to
      # the secure secrets you must set up in the Codemagic web UI.
      vars:
        # Shorebird Token (must be uploaded as a secure secret)
        SHOREBIRD_TOKEN: $SHOREBIRD_TOKEN 
        
        # Android Signing Credentials (must be uploaded as secure secrets)
        CM_KEYSTORE_PATH: $CM_KEYSTORE_PATH
        CM_KEYSTORE_PASSWORD: $CM_KEYSTORE_PASSWORD
        CM_KEY_ALIAS: $CM_KEY_ALIAS
        CM_KEY_PASSWORD: $CM_KEY_PASSWORD

    # 3. CACHING: Speeds up subsequent builds significantly.
    cache:
      cache_paths:
        # FIX 3: Removed extra spaces for valid list format
        - .gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.cocoapods/repos
        - $HOME/.pub-cache

    # 4. START SCRIPTS
    scripts:
      # A. PRE-BUILD SCRIPT: Installs Shorebird CLI and logs in securely.
      - name: Set up Shorebird
        script: |
          #!/bin/sh
          # Install Shorebird CLI
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          export PATH="$PATH:$HOME/.shorebird/bin"
          
          # Log in using the secure token
          # This line uses the token reference correctly.
          shorebird login --ci --token "$SHOREBIRD_TOKEN"

      # B. MAIN BUILD SCRIPT: Builds the app with Shorebird.
      - name: Build Android Release (APK) with Shorebird
        script: |
          #!/bin/sh
          export PATH="$PATH:$HOME/.shorebird/bin"
          cd $CM_BUILD_DIR
          
          # Run tests before building (optional, but highly recommended)
          flutter test
          
          # CRITICAL: Use --apk-build-mode release to force an APK output
          shorebird release android --apk-build-mode release
          
    # 5. ARTIFACTS: Defines where the final APK file can be found.
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
