name: my_plant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # It's good practice to define an SDK range

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  camera: ^0.10.5
  http: ^1.2.1
  dio: ^5.7.0
  http_parser: ^4.0.2
  flutter_dotenv: ^5.1.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  google_generative_ai: ^0.2.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  image: ^4.2.0
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  app_links: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  flutter_launcher_icons: "^0.13.1"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21